USE PROJECT_MEDICAL_DATA_HISTORY;

SELECT * FROM ADMISSIONS;
SELECT * FROM DOCTORS;
SELECT * FROM PATIENTS;
SELECT * FROM PROVINCE_NAMES;


# 1. SHOW FIRST NAME, LAST NAME, AND GENDER OF PATIENTS WHOSE GENDER IS 'M'.

	 SELECT FIRST_NAME,
     LAST_NAME,
     GENDER 
     FROM PATIENTS 
     WHERE GENDER = 'M';                          # TOTAL MALE PATIENTS - 2468

# 2. SHOW FIRST NAME AND LAST NAME OF PATIENTS WHO DON'T HAVE ANY ALLERGIES.
     
     SET SQL_SAFE_UPDATES = 0;
     UPDATE PATIENTS
     SET ALLERGIES = NULL 
     WHERE ALLERGIES = 'NKA';
     SET SQL_SAFE_UPDATES = 1;
     
     SELECT FIRST_NAME,
     LAST_NAME 
     FROM PATIENTS
     WHERE ALLERGIES IS NULL; 
     
     SELECT * FROM PATIENTS;                       # 2059 NULL RECORDS 


# 3.SHOW FIRST NAME OF PATIENTS WHOSE NAMES START WITH THE LETTER 'C'.

    SELECT  FIRST_NAME 
	FROM PATIENTS 
    WHERE FIRST_NAME LIKE'C%';                    # TOTAL PATIENTS - 302


# 4. SHOW FIRST NAME AND LAST NAME OF PATIENTS THAT WEIGH WITHIN THE RANGE OF 100 TO 120 (INCLUSIVE).

     SELECT FIRST_NAME,
     LAST_NAME 
     FROM PATIENTS 
     WHERE WEIGHT BETWEEN 100 AND 120;                 #  TOTAL PATIENTS - 952


# 5. UPDATE THE PATIENTS TABLE FOR THE ALLERGIES COLUMN. IF A PATIENT'S ALLERGY IS NULL THEN REPLACE IT WITH 'NKA'.

     
     SET SQL_SAFE_UPDATES = 0;

     UPDATE PATIENTS 
     SET ALLERGIES = 'NKA' 
     WHERE ALLERGIES IS NULL;                   
	 
     SET SQL_SAFE_UPDATES = 1;
     
     SELECT * FROM PATIENTS;                    # 2059 PATIENTS' RECORDS CHANGED
     
    


# 6. SHOW FIRST NAME AND LAST NAME CONCATENATED INTO ONE COLUMN TO SHOW THEIR FULL NAME.

     SELECT 
     CONCAT(FIRST_NAME,' ',LAST_NAME) 
     AS FULL_NAME 
	 FROM PATIENTS;                            # 4530 RECORDS


# 7. SHOW FIRST NAME, LAST NAME, AND THE FULL PROVINCE NAME OF EACH PATIENT.
     
     SELECT FIRST_NAME,
     LAST_NAME,
     PROVINCE_NAME 
     FROM PATIENTS 
     JOIN PROVINCE_NAMES 
     ON PATIENTS.PROVINCE_ID = PROVINCE_NAMES.PROVINCE_ID;         # 4530 RECORDS 


# 8. SHOW THE NUMBER OF PATIENTS WHOSE BIRTH_DATE IS IN THE YEAR 2010.
     
     SELECT 
     COUNT(*) AS TOTAL 
     FROM PATIENTS 
     WHERE YEAR(BIRTH_DATE) = 2010;            # 55 RECORDS COUNTED


# 9. SHOW THE FIRST_NAME, LAST_NAME, AND HEIGHT OF THE PATIENT WITH THE GREATEST HEIGHT.
     SELECT FIRST_NAME,
     LAST_NAME,
     HEIGHT 
     FROM PATIENTS 
     ORDER BY HEIGHT DESC 
     LIMIT 1;                                               /* FIRST NAME - SAM
                                                               LAST NAME - HARUKO
                                                               HEIGHT - 226 CM */


# 10. SHOW ALL COLUMNS FOR PATIENTS WHO HAVE ONE OF THE FOLLOWING PATIENT_IDS: 1,45,534,879,1000.
	  
      SELECT * FROM PATIENTS 
      WHERE PATIENT_ID IN (1,45,534,879,1000);                  /* NAMES - DONALD WATERFALL
                                                                           CROSS GORDON
                                                                           DON ZATARA
                                                                           ORLA SHAWN
                                                                           RICK WILLIAMS */


# 11. SHOW THE TOTAL NUMBER OF ADMISSIONS.
      
      SELECT 
      COUNT(PATIENT_ID) AS TOTAL_NUM 
      FROM ADMISSIONS;                            # 5067 RECORDS                               


# 12. SHOW ALL THE COLUMNS FROM ADMISSIONS WHERE THE PATIENT WAS ADMITTED AND DISCHARGED ON THE SAME DAY.
      
      SELECT * FROM ADMISSIONS 
      WHERE ADMISSION_DATE = DISCHARGE_DATE;          # 481 RECORDS


# 13. SHOW THE TOTAL NUMBER OF ADMISSIONS FOR PATIENT_ID 579.
      SELECT 
	  COUNT(PATIENT_ID) AS TOTAL_ID 
      FROM ADMISSIONS 
      WHERE PATIENT_ID = 579;                     # TOTAL COUNTS - 2


# 14. BASED ON THE CITIES THAT OUR PATIENTS LIVE IN, SHOW UNIQUE CITIES THAT ARE IN PROVINCE_ID 'NS'.
      
      SELECT DISTINCT CITY AS CITY_NS,
      PROVINCE_ID 
      FROM PATIENTS 
      WHERE PROVINCE_ID = 'NS';                       /* CITIES NAMES - PORT HAWKESBURY
																		HALIFAX
                                                                        INVERNESS */


# 15. WRITE A QUERY TO FIND THE FIRST_NAME,LAST_NAME AND BIRTH_DATE OF PATIENTS WHOSE HEIGHT IS GREATER THAN 160 AND WEIGHT IS GREATER THAN 70.
      
      SELECT FIRST_NAME,
      LAST_NAME,
      BIRTH_DATE 
      FROM PATIENTS 
      WHERE HEIGHT > 160 
      AND WEIGHT > 70 
      ORDER BY BIRTH_DATE;                            # 2091 RECORDS


# 16. SHOW UNIQUE BIRTH YEARS FROM PATIENTS AND ORDER THEM IN ASCENDING ORDER.
      
      SELECT DISTINCT YEAR(BIRTH_DATE) AS YEARS 
      FROM PATIENTS 
      ORDER BY YEARS;                            # 93 RECORDS


# 17. SHOW UNIQUE FIRST NAMES FROM THE PATIENTS TABLE WHICH ONLY OCCURS ONCE IN THE LIST.
      
      SELECT FIRST_NAME 
      FROM PATIENTS 
      GROUP BY FIRST_NAME 
      HAVING COUNT(*) = 1 
      ORDER BY FIRST_NAME;                        # 319 RECORDS


# 18. SHOW PATIENT_ID AND FIRST_NAME FROM PATIENTS WHERE THEIR FIRST_NAME STARTS AND ENDS WITH 'S' AND IS AT LEAST 6 CHARACTERS LONG.
      
      SELECT PATIENT_ID,
      FIRST_NAME 
      FROM PATIENTS 
      WHERE FIRST_NAME LIKE 'S%_S'
      AND LENGTH(FIRST_NAME) >= 6;                       # 11 RECORDS


/* 19. SHOW PATIENT_ID, FIRST_NAME AND LAST_NAME FROM PATIENTS WHOSE DIAGNOSIS IS 'DEMENTIA'.
	  THE PRIMARY DIAGNOSIS IS STORED IN THE ADMISSIONS TABLE.*/

      SELECT T1.PATIENT_ID,
      T1.FIRST_NAME,
      T1.LAST_NAME,
      T2.DIAGNOSIS
      FROM PATIENTS T1 
      JOIN ADMISSIONS T2 
      ON T1.PATIENT_ID = T2.PATIENT_ID 
      WHERE T2.DIAGNOSIS = 'DEMENTIA';                       # 26 RECORDS


# 20. DISPLAY EVERY PATIENT'S FIRST_NAME. ORDER THE LIST BY THE LENGTH OF EACH NAME AND THEN ALPHABETICALLY.
      
      SELECT FIRST_NAME 
      FROM PATIENTS 
      ORDER BY LENGTH(FIRST_NAME),FIRST_NAME;                     # 4530 RECORDS


/* 21. SHOW THE TOTAL AMOUNT OF MALE PATIENTS AND THE TOTAL AMOUNT OF FEMALE PATIENTS IN THE PATIENTS TABLE. 
	   DISPLAY THE TWO RESULTS IN THE SAME ROW. */
       
       SELECT 
       SUM(CASE WHEN GENDER ='M' THEN 1 ELSE 0 END) AS PATIENT_MALE,
	   SUM(CASE WHEN GENDER = 'F' THEN 1 ELSE 0 END) AS PATIENT_FEMALE 
       FROM PATIENTS;                                                   # MALE - 2468 | FEMALE - 2062


# 22. SHOW PATIENT_ID AND DIAGNOSIS FROM ADMISSIONS. FIND PATIENTS WHO WERE ADMITTED MULTIPLE TIMES FOR THE SAME DIAGNOSIS.
      
      SELECT PATIENT_ID,
      DIAGNOSIS 
      FROM ADMISSIONS 
      GROUP BY PATIENT_ID,DIAGNOSIS 
      HAVING COUNT(*) > 1;                        # 11 RECORDS


# 23.  SHOW THE CITY AND THE TOTAL NUMBER OF PATIENTS IN THE CITY. ORDER FROM MOST TO LEAST PATIENTS AND THEN BY CITY NAME ASCENDING.
       
       SELECT CITY,
       COUNT(PATIENT_ID) AS TOTAL_PATIENTS 
       FROM PATIENTS 
       GROUP BY CITY 
       ORDER BY TOTAL_PATIENTS DESC,
       CITY;                                                 

       SELECT CITY,
       COUNT(PATIENT_ID) AS TOTAL_PATIENTS 
       FROM PATIENTS 
       GROUP BY CITY 
       ORDER BY CITY;                                   /* MOST PATIENTS | CITY: HAMILTON - 1938
                                                           LEAST PATIENTS | CITIES: LINTON | ROCKFORD | URETERBURG - 1 */ 


# 24.  SHOW FIRST NAME, LAST NAME AND ROLE OF EVERY PERSON WHO IS EITHER A PATIENT OR A DOCTOR. THE ROLES ARE EITHER "PATIENT" OR "DOCTOR".
       
       SELECT FIRST_NAME,
       LAST_NAME,
	   'PATIENT' AS ROLE FROM PATIENTS
       UNION ALL
	   SELECT FIRST_NAME,
       LAST_NAME,
       'DOCTOR' AS ROLE FROM DOCTORS;                      # 4557 RECORDS


# 25. SHOW ALL ALLERGIES ORDERED BY POPULARITY. EXCLUDE NULL VALUES FROM THE RESULT.
      
      SELECT ALLERGIES,
      COUNT(*) AS TOTAL_COUNT 
      FROM PATIENTS 
      WHERE ALLERGIES IS NOT NULL 
      GROUP BY ALLERGIES 
      ORDER BY TOTAL_COUNT DESC;                           # 64 RECORDS


/*26. SHOW ALL PATIENT'S FIRST_NAME, LAST_NAME, AND BIRTH_DATE WHO WERE BORN IN THE 1970S DECADE. 
	  SORT THE LIST STARTING FROM THE EARLIEST BIRTH_DATE. */
	
      SELECT FIRST_NAME,
	  LAST_NAME,
	  BIRTH_DATE 
	  FROM PATIENTS 
	  WHERE BIRTH_DATE BETWEEN '1970-01-01' AND '1979-12-31' 
	  ORDER BY BIRTH_DATE;                                 # 623 RECORDS


/* 27. WE WANT TO DISPLAY EACH PATIENT'S FULL NAME IN A SINGLE COLUMN.
       THEIR LAST_NAME IN ALL UPPER LETTERS MUST APPEAR FIRST, THEN FIRST_NAME IN ALL LOWER CASE LETTERS.
       SEPARATE THE LAST_NAME AND FIRST_NAME WITH A COMMA. ORDER THE LIST BY THE FIRST_NAME IN DECENDING ORDER    EX: SMITH,JANE */
       
       SELECT CONCAT_WS(',',UPPER(LAST_NAME),LOWER(FIRST_NAME)) AS FULL_NAME 
       FROM PATIENTS 
       ORDER BY FIRST_NAME DESC;                              # STARTS WITH - MILLER,zoe


# 28. SHOW THE PROVINCE_ID(S) AND THE SUM OF HEIGHT; WHERE THE TOTAL SUM OF ITS PATIENTS' HEIGHTS IS GREATER THAN OR EQUAL TO 7,000 CM.
	  
      SELECT PROVINCE_ID,
      SUM(HEIGHT) AS TOTAL_HEIGHT
      FROM PATIENTS 
      GROUP BY PROVINCE_ID 
      HAVING TOTAL_HEIGHT >= 7000 
      ORDER BY TOTAL_HEIGHT DESC;                            /* PROVINCE_IDS | HEIGHTS: ON - 6,78,037 CM                                          
                                                                                   NS - 9,765 CM
                                                                                   BC - 7720 CM */

# 29.  SHOW THE DIFFERENCE BETWEEN THE HIGHEST WEIGHT AND LOWEST WEIGHT FOR PATIENTS WITH THE LAST NAME 'MARONI'.
       
       SELECT MAX(WEIGHT) - MIN(WEIGHT) AS MEASURED_WEIGHT 
       FROM PATIENTS 
       WHERE LAST_NAME = 'MARONI';                           # DIFFERENCE - 71 KGS


/* 30. SHOW ALL OF THE DAYS OF THE MONTH (1-31) AND HOW MANY ADMISSION_DATES OCCURRED ON THAT DAY. 
	   SORT BY THE DAY WITH MOST ADMISSIONS TO LEAST ADMISSIONS. */
	   
       SELECT DAY(ADMISSION_DATE) AS ADMISSION_DAY, 
       COUNT(ADMISSION_DATE) AS ADMISSION_NUMBERS
	   FROM ADMISSIONS 
       GROUP BY ADMISSION_DAY 
       ORDER BY ADMISSION_NUMBERS DESC;                  # 31 RECORDS


/* 31. SHOW ALL OF THE PATIENTS GROUPED INTO WEIGHT GROUPS. SHOW THE TOTAL AMOUNT OF PATIENTS IN EACH WEIGHT GROUP.
	   ORDER THE LIST BY THE WEIGHT GROUP DECENDING. 
	   E.G. IF THEY WEIGHT 100 TO 109 THEY ARE PLACED IN THE 100 WEIGHT GROUP, 110-119 = 110 WEIGHT GROUP, ETC. */
       
       SELECT COUNT(PATIENT_ID) AS TOTAL_PATIENTS, 
       FLOOR(WEIGHT/10)*10 AS WEIGHT_GROUP
       FROM PATIENTS 
       GROUP BY WEIGHT_GROUP 
       ORDER BY WEIGHT_GROUP DESC;                         # 15 RECORDS


/* 32. SHOW PATIENT_ID, WEIGHT, HEIGHT, ISOBESE FROM THE PATIENTS TABLE. 
       DISPLAY ISOBESE AS A BOOLEAN 0 OR 1. OBESE IS DEFINED AS WEIGHT(KG)/(HEIGHT(M).
	   WEIGHT IS IN UNITS KG. HEIGHT IS IN UNITS CM. */
      
       SELECT PATIENT_ID, 
       WEIGHT, 
       HEIGHT, 
       CASE  
           WHEN WEIGHT / POWER(HEIGHT / 100.0, 2) >= 30 THEN 1 ELSE 0  
       END AS ISOBESE  
       FROM PATIENTS;                                                       # 4530 RECORDS


/* 33.  SHOW PATIENT_ID, FIRST_NAME, LAST_NAME, AND ATTENDING DOCTOR'S SPECIALTY. 
        SHOW ONLY THE PATIENTS WHO HAS A DIAGNOSIS AS 'EPILEPSY' AND THE DOCTOR'S FIRST NAME IS 'LISA'. 
		CHECK PATIENTS, ADMISSIONS, AND DOCTORS TABLES FOR REQUIRED INFORMATION. */
		
        SELECT P.PATIENT_ID, 
        P.FIRST_NAME,
        P.LAST_NAME,
        D.SPECIALTY
        FROM PATIENTS P
	    JOIN ADMISSIONS A ON P.PATIENT_ID = A.PATIENT_ID
        JOIN DOCTORS D ON A.ATTENDING_DOCTOR_ID = D.DOCTOR_ID
		WHERE A.DIAGNOSIS = 'EPILEPSY' AND D.FIRST_NAME ='LISA';              # 2 RECORDS


/* 34.  ALL PATIENTS WHO HAVE GONE THROUGH ADMISSIONS, CAN SEE THEIR MEDICAL DOCUMENTS ON OUR SITE.
        THOSE PATIENTS ARE GIVEN A TEMPORARY PASSWORD AFTER THEIR FIRST ADMISSION.
		SHOW THE PATIENT_ID AND TEMP_PASSWORD. /*

/*      THE PASSWORD MUST BE THE FOLLOWING, IN ORDER:
        - PATIENT_ID
        - THE NUMERICAL LENGTH OF PATIENT'S LAST_NAME
        - YEAR OF PATIENT'S BIRTH_DATE
*/
        SELECT P.PATIENT_ID, 
		CONCAT(P.PATIENT_ID, 
		LENGTH(P.LAST_NAME), 
		YEAR(P.BIRTH_DATE)) AS TEMP_PASSWORD
        FROM PATIENTS P
        JOIN ADMISSIONS A 
        ON P.PATIENT_ID = A.PATIENT_ID
        GROUP BY P.PATIENT_ID, P.LAST_NAME, P.BIRTH_DATE;                      # 4530 RECORDS


-- THE END --









